### ISSUE TITLE
issues extending due to VOLUME ["/opt/red5"] 

### ISSUE THREAD

**Issue by virtualfunction** [Red5/docker#2]
Because of VOLUME ["/opt/red5"] in the base Dockerfile if I do something like:

`COPY target/some_web_app /opt/red5/webapps/`

those files won't COPY into /opt/red5 because further modifications to /opt/red5 has been declared to be excluded from the AUFS layer from the VOLUME.

The VOLUME command should probably be left to users extending the Docker image and restricted to things like the log folders if they are included.

Also, is there any reason Java8 versions of the Dockerfile aren't included here?

**Comment by mondain** [comment]
I'm planning to remove the volume entry as well as offer java 8 versions.

**Comment by mondain** [comment]
VOLUME has been removed from the base images and a jdk8 version has been added.

**Comment by virtualfunction** [comment]
Awesome. Thanks :)
